### ISSUE TITLE
event.json is not passed?

### ISSUE THREAD

**Issue by kvanlombeek** [robhowley/lambda-warmer-py#11]
Ref screenshots, 

I passed the event.json with the required parameters, 

But he doesn't seem to find these parameters within the wrapper function.

![Screen Shot 2019-04-28 at 11 10 41 AM](https://user-images.githubusercontent.com/8471898/56861957-500c9400-69a6-11e9-85c8-2851c0ec20a3.png)
<img width="538" alt="Screen Shot 2019-04-28 at 11 05 14 AM" src="https://user-images.githubusercontent.com/8471898/56861965-5c90ec80-69a6-11e9-872e-a628a74a1621.png">

**Comment by robhowley** [comment]
Interesting. I won’t be able to look into it until tomorrow morning, but there def appears to be a py2->3 inconsistency going on. none comparisons changed between versions. Not sure if that’s your cause but it’s an issue to address nonetheless

Consider this acknowledged. I’ll keep you posted.
 
Do you get that error with concurrency = 1?

Thanks for giving the package a try.

**Comment by kvanlombeek** [comment]
Hi, I already found another plugin, https://github.com/FidelLimited/serverless-plugin-warmup, so I am not going to debug further. Thank you for you answer.

**Comment by robhowley** [comment]
it was a compatibility issue. now fixed. thanks.
