### ISSUE TITLE
Not Logging metrics to cloudwatch

### ISSUE THREAD

**Issue by chamakov** [robhowley/lambda-warmer-py#13]
I'm haing an issue when trying to log metrics to cloudwatch, I'm not seeing anything, I'm sending this json as payload:

{ "warmer": true, "concurrency": 6, "send_metric" : true }

also the decorator is on the function

Any suggestion?

**Comment by robhowley** [comment]
the most common issue with that is one of permissions. does the lambda have cloudwatch permissions to put metric data? if you have code snippets and/or aws console screenshots on your configuration, that would be helpful. cloudwatch logs from your lambda execution would also be helpful.

thanks!

**Comment by mvanbaak** [comment]
~~This is actually a bug.~~

~~The warmer() method has the send_metric argument with default False as value. From there, the variable is never changed, so it is False all the time.~~

~~What's missing is a call to event.get('send_metric') to get the actual knob from the event json to enable the metric sending this way.~~

[EDIT]
I did not read the bugreport correctly.
The sending of metric data is NOT managed by setting the field in the event json. It's a function argument for the decorator.

```python
@lambdawarmer.warmer(send_metric=True)
def lambda_handler(event, context):
```

@chamakov This is how you enable the custom metrics in cloudwatch

**Comment by robhowley** [comment]
@mvanbaak thanks for helping @chamakov out on my behalf. i updated the readme to make the clearer. sorry for misreading your post on first pass.
