### ISSUE TITLE
handler not a function

### ISSUE THREAD

**Issue by yeyeric** [robhowley/lambda-warmer-py#24]
Hello,

I'm using framework fastApi with mangum for my lambda functions.

Therefore, here is my code to make my app serverless:

```
from fastapi import FastAPI
from mangum import Mangum
import lambdawarmer

app = FastAPI()

@lambdawarmer.warmer
handler = Mangum(app)

```

This works perfectly without the @lambdawarmer.warmer line

 BUT, this doesn't work as handler should be a function as per your guide.

How should I manage such case ?

Thanks

**Comment by robhowley** [comment]
sorry, i'm not familiar w those frameworks. but yea, handlers should be functions for this.
