### ISSUE TITLE
cloud watch rule format

### ISSUE THREAD

**Issue by zogak** [robhowley/lambda-warmer-py#25]
I read README, applied warmer to my lambda.
It seems that json format
```
{
    "warmer": true,
    "concurrency": 1
}
```
written here does not fit what aws requires...
How can I apply event pattern then?

Also, just wondering the reason for using lambda-warmer, not just ping lambda every constant minute using aws cloud watch event bridge.

**Comment by zogak** [comment]
just found right place to put those json texts :)
wonder it's logic then, with just a decorator, if lambda is called by this event rule, not by users, does it quit without performing original codes that I wrote inside the lambda?

**Comment by robhowley** [comment]
Hey, thanks for reaching out and sorry for the delay. Your understanding is
correct. If it’s a “warmer” invocation, the main method you wrote won’t run. It’ll get skipped in the highlighted section below. Note, your function is in the else. If you set it up to keep multiple lambdas warm, that’ll be taken care of by the fan out.

Hope that helps. If not I’ll be of more assistance when I’m back at my
computer next week.

**Comment by zogak** [comment]
Thank you for your answer!
