### ISSUE TITLE
The warmer decorator should short-circuit

### ISSUE THREAD

**Issue by DrGodCarl** [robhowley/lambda-warmer-py#9]
Maybe I'm off-base here, but it seems like we want to decorate the function so we don't have to think about handling the warming event in any way at all in our code. As it's written, I still have to write custom handling logic for when the warming event comes in. If this change doesn't make sense could you either correct me in my usage or explain to me why it makes sense not to short-circuit inside the decorator?

**Comment by robhowley** [comment]
should short circuit [here](https://github.com/robhowley/lambda-warmer-py/blob/master/lambdawarmer/__init__.py#L74) at the check for whether or not this is a warmer invocation. that value is extracted from the event received by the lambda [here](https://github.com/robhowley/lambda-warmer-py/blob/master/lambdawarmer/__init__.py#L33). 

in the original js version in the `lambda-warmer` repo it does look like you need to add a function call at the top but i'm certainly not js savvy so take that w a grain of salt. here you're adding the decorator up top, getting your lambda handler wrapped w the check and warmup call, and doing nothing else.

you'll always need to have the "ping" event from cloudwatch or whatever w the appropriate event data configured. 

if i have a bug where it's not short circuiting def let me know.

**Comment by DrGodCarl** [comment]
The way I'm reading it (and the way it seemed to behave), when I'd decorate with `@lambdawarmer.warmer()` it would perform your warming stuff, as stated, but would still always hit my handler function. I know the JS library requires custom handling but it seems like you wanted this to be a drop-in solution where all you have to do is annotate and your regular events flow through and your warming events don't. What I mean is that [this](https://github.com/robhowley/lambda-warmer-py/blob/master/lambdawarmer/__init__.py#L48) always gets called rather than seeing that the `warmer` key is set on the event and just skipping the handler altogether.

**Comment by robhowley** [comment]
oh whoops thanks. will update later today. was thinking about skipping warm up calls and forgot about skipping actual calls.

**Comment by DrGodCarl** [comment]
Awesome! Thanks for being such a responsive maintainer.

**Comment by robhowley** [comment]
@DrGodCarl #10 moves the conditional into the decorator to skip the wrapped lambda on warmer invoke and updated the test for it. thanks again.

**Comment by robhowley** [comment]
v 0.3.0 up on pypi
